name: Pipeline
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  registry_package:
    types: [ published, updated ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup builder
        run: docker buildx create --bootstrap --use
      - name: Build image for testing
        run: >
          docker buildx build --target test 
          --cache-to type=registry,ref=ghcr.io/wojciechem/legacy:latest-cache 
          --push 
          -t ghcr.io/wojciechem/legacy:latest .