name: Pipeline
on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]
  registry_package:
    types: [ published, updated ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.output-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup builder
        run: docker buildx create --bootstrap --use
      - name: Build image for testing
        run: >
          docker buildx build --target test 
          --cache-from type=registry,ref=ghcr.io/wojciechem/legacy:latest-cache 
          --cache-to type=registry,ref=ghcr.io/wojciechem/legacy:latest-cache 
          --pull
          --push 
          -t ghcr.io/wojciechem/legacy:latest-test 
          -t ghcr.io/wojciechem/legacy:${GITHUB_SHA}-test .
      - name: output-tag
        run: echo "tag=${GITHUB_SHA}" >> "$GITHUB_OUTPUT"
  test:
    needs: build
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/wojciechem/legacy:${{ needs.build.outputs.tag }}-test
    steps:
      - name: Smoke test
        run: vendor/bin/phpunit --filter AlivenessTest
